setwd("C:\\Users\\EdisonPan\\Desktop\\bishe")
rt<-read.table("raw_th")
vn<-rownames(rt)
ry<-t(rt)
m<-as.matrix(ry)
class(m)
n<-nrow(m)
library(pcalg)
pc.fit<-pc(suffStat = list(C=cor(m), n=n), indepTest = gaussCItest, alpha = 0.2, labels = vn)
g<-skeleton(suffStat = list(C=cor(m), n=n), indepTest = gaussCItest, alpha = 0.1, labels = vn)
png(file="test.png", bg = "transparent")
par(mfrow=c(1,3))
plot(pc.fit, main="test")
plot(g)
dev.off()

mat <- as(pc.fit@graph,'matrix')
write.table(mat, file = "b.txt", sep=" ")  

#Save as a jpeg(pdf or png)
#setwd()
#jpeg(file="test.jpeg")
#png(file="test.png", bg="transparent")
#pdf(file="test.pdf")
#plot(g)
#dev.off()
